### ISSUE TITLE
Preload Json

### ISSUE THREAD

**Issue by bitcoinment** [ddhp/react-isomorphic-boilerplate#28]
How to prerender html-dom for SEO from json-request before load the page (inside react)?

**Comment by ddhp** [comment]
This boilerplate takes benefit from [redux](https://redux.js.org/) to manage data/states, and one important concept of redux is you always manipulate your app state through actions.

So in order to get json data for SEO, you need to define an action for it, then invoke it at [loadData hook](https://github.com/ddhp/react-isomorphic-boilerplate/blob/master/src/routes/main.js#L41) (you can config it for different path). And then you will have expected data while rendering your container.

**Comment by bitcoinment** [comment]
@ddhp Thanks!

**Comment by ddhp** [comment]
you are very welcome!
