### ISSUE TITLE
Browser rendering doesn't call the loadData of the route

### ISSUE THREAD

**Issue by Strobotti** [ddhp/react-isomorphic-boilerplate#32]
With just git clone, yarn install & build steps as instructed on readme the server-side rendering works perfectly, but the browser-side doesn't apparently call the loadData-method(s) on routes.

To reproduce the issue:

1. On "home" page submit a message, which appears correctly
1. Navigate to "about" page
1. Hard-reload to get the server-rendered version
1. navigate back to "home" page; The submitted message is missing
1. Hard-reload and the messages appear

Some details:

```
$ npm --version
6.1.0

$ yarn --version
1.7.0

$ node --version
v9.11.2
````

**Comment by Strobotti** [comment]
So the server rendering part calls the `loadData` in this method:
https://github.com/ddhp/react-isomorphic-boilerplate/blob/master/src/server/renderer.js#L54

But it's not called anywhere else nor there is any similar functionality on the "browser path".

**Comment by ddhp** [comment]
Files under `src/routes` are executed both on server side and browser,
but unfortunately `loadData` in function `getRoutes` is intentionally designed to be only executed on server side.
Because this hook is for the purpose of getting data for SEO, which can potentially be different from the data you want to show to real users on client.

So please check PR #33  to see how to fetch initial data on SPA client! 

I know it's a bit cumbersome if your data for SEO and client is the same,
but that's the situation you have to deal with as an isomorphic/universal app
and sometimes you have to do different behavior on server and client.

**Comment by ddhp** [comment]
close due to inactivity
